# Python CircleCI 2.0 configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    resource_class: small
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./requirements/dev.txt
      # Step 3: run linter and tests
      - run:
          name: run quality test
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics --config flake8
      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            pytest -v --cov=clean_fem
      - run:
          name: run security tests
          command: |
            . venv/bin/activate
            bandit -r /home/circleci/repo --exclude /home/circleci/repo/venv --configfile bandit.yaml
      # curl -Os https://uploader.codecov.io/latest/linux/codecov chmod +x codecov ./codecov
